version: '3'
services:
  test:
    build: tests/
    networks:
       - overlay
    depends_on:
      - web
  web:
    build: .
    image: "syncthecity/syncthecity-baltimore:${CIRCLE_SHA1}"
    networks:
       - overlay
    ports:
     - "3838:3838"

networks:
  overlay:
