version: '3'
services:
  api:
    build: .
    # depends_on: 
    #   - db
    # links:
    #   - "db: database"
    ports:
      - '5000:5000'
    command: python manage.py
    # volumes:
    #   - ./citysync/:/root/citysync
    # env_file: .env
  # db:
  #   image: postgres
  #   restart: always
  #   environment:
  #     - POSTGRES_USER=${DATABASE_USER}
  #     - POSTGRES_PASSWORD=${DATABASE_PASSWORD}