version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Check for changed files
          command: |
                  set +e
                  git log -m -1 --name-only --pretty="format:" | grep -i packrat
                  if [ $? -eq 0 ]; then
                        printf '%s\n' "packrat changed"
                        docker build . -f Dockerfile.base -t "syncthecity/syncthecity-base:latest"
                  else
                        printf '%s\n' "No dependancies changed"
                  fi
